language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: releases
  api_key:
    secure: IQU4c9XEBBk14pbRbSe4obGSlQ/CDZTAXaMZK17pre+ZOv4snjV8cwxIlzCa9GhKqHWxYaBq37e4lQ7cl/WCW17sssq50SewbfsxJT6DbBSPn9bNKjZIQL6cq4oy1Uo2wS42oxQcNBeDalrVGMDCtV1Kfzc7FU9TKtfW2kQ8SPJr6cR/YRhAUaKUgWYN0OevIF4CTbSTHXJJR1lZwPj6EVJ9Cm9Hbgq8zj3+vYFZ4QAaZjbEClN79XIxwI0dDFqS95WjXL4ccl10tC9JU9etW0zrkSWwDvbYuPmFwKd/K+sA1qb1pnmjrley5U1Jtr+V0cwO1WIiUzVK9nJoCalsiTpsRdD+oFQ+jyhYEG4fY6XFacwSLk0FYZYzR6Uu20IvofZXRXAsu6Rd0UdGCh7dYbsW8pfJkJgl5L8Mcx0H3LN/tOqA9qzQR6t3K81RZEqd1MfrnXj7inxZSQYNJrQiRK0MSVL4aIYsQJd+OVQtWPSR3v5ehfqnq50rC5clGITlRMJvgnxn1c2Fgy7w6mM2I7uElxWpjCIrFwU3zQcv1+UMF1IiLhtLnyVZg9DV7qyahNJCWQnLuP3ydHCbF9etH8LB17MlmpYkwVhHN8byy+N6J+jsUggoiYoGbYsCnNkLoINLJ1WAsgQAsRWUf/iArPypEEDD8Tby3psvvVv2jRk=
  file_glob: true
  file: "./build/libs/JAlgoArena-Submissions-*.zip"
  skip_cleanup: true
  on:
    repo: skorzeniak/JAlgoArena-Submissions
    tags: true
