logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://sk-jalgoarena-eureka.herokuapp.com/eureka

server:
  port: ${PORT:5003}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:jalgoarena-submissions}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
